spring.application.name=SpringSecurityDemo

spring.security.user.name=mani

spring.security.user.password=sunny

spring.datasource.url=jdbc:mysql://localhost:3306/sunny
spring.datasource.username = root
spring.datasource.password = root

